language: shell # minimal

os:
  - linux

dist: bionic

branches:
  only:
    - master
    - development

services:
  - docker

env:
  - SHA=$(git rev-parse --short=7 HEAD)

before_install:
  - |
    docker image build \
      -f ./client/development.Dockerfile \
      -t juliocesarmidia/search-cities-client:latest \
      -t juliocesarmidia/search-cities-client:$SHA \
      ./client

script:
  - |
    docker container run --rm \
      --name search-cities-client \
      juliocesarmidia/search-cities-client:latest \
      npm run lint
