sudo: required
services:
  - docker

env:
  - SHA=$(git rev-parse HEAD)

before_install:
  - docker image build -t juliocesarmidia/search-cities-front -f Dockerfile-front-dev .

script:
  - docker container run --name search-cities-front -p 8090:80 juliocesarmidia/search-cities-front npm run lint