version: '3'
services:
  front:
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile-front
    ports:
      - 8090:80
    restart: always
    environment:
      API_HOST: api:9000
  db:
    container_name: db
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_vue_select
    volumes:
      - mysql-db:/var/lib/mysql
      - ./api/data.sql:/docker-entrypoint-initdb.d/data.sql
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile-back
    ports:
      - 9000:9000
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: admin
      DB_DATABASE: db_vue_select
      API_PORT: 9000

volumes:
  mysql-db:
