version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty

    steps:
      - checkout

      - run:
          name: Install Docker client
          command: |
            set -x
            DOCKER_VERSION="18.06.0-ce"
            curl -L -o /tmp/docker-$DOCKER_VERSION.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$DOCKER_VERSION.tgz
            tar -xz -C /tmp -f /tmp/docker-$DOCKER_VERSION.tgz
            mv /tmp/docker/* /usr/bin

      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: false

      - run:
          name: Build Docker image
          command: |
            SHA=$(git rev-parse --short=7 HEAD)

            docker image build \
              -f ./client/development.Dockerfile \
              -t juliocesarmidia/search-cities-client:latest \
              -t juliocesarmidia/search-cities-client:$SHA \
              ./client

            docker container run --rm \
              --name search-cities-client \
              juliocesarmidia/search-cities-client:latest \
              npm run lint
