version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty

    steps:
      - checkout

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: true

      - run:
          name: Build Docker image
          command: |
            SHA=$(git rev-parse HEAD)
            docker image build -t juliocesarmidia/search-cities-front:$SHA -f Dockerfile-front-dev .
            docker container run --name search-cities-front -p 8090:80 juliocesarmidia/search-cities-front:$SHA npm run lint
